include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    use_string_in_part_of_directives: ignore
  exclude: 
    - '**/*.g.dart'

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true