name: comgred
description: "Computer Graphics Editor"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  file_picker: ^8.1.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  go_router: ^14.6.2
  input_quantity: ^2.5.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  multi_split_view: ^3.6.0
  path: ^1.9.0
  path_provider: ^2.1.5
  vector_math: ^2.1.4
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
